export const OWNER_ROLE = "owner";
export const MANAGER_ROLE = "manager";
export const SUPERVISOR_ROLE = "supervisor";
export const OPERATOR_ROLE = "operator";
export const ACCOUNTANT_ROLE = "accountant";
export const AUDITOR_ROLE = "auditor";
export const ADMIN_ROLE = "admin";
export const INVENTORY_ROLE = "inventory";
export const SALES_ROLE = "sales";

export const USER_MANAGEMENT_ROLES = [OWNER_ROLE, MANAGER_ROLE];
export const HISTORICAL_IMPORT_ROLES = [OWNER_ROLE, MANAGER_ROLE];
export const OPERATIONAL_DATA_ROLES = [OWNER_ROLE, MANAGER_ROLE, SUPERVISOR_ROLE];
export const PRODUCTION_INPUT_ROLES = [OWNER_ROLE, MANAGER_ROLE, SUPERVISOR_ROLE, OPERATOR_ROLE];
export const EXPENSE_DATA_ROLES = [OWNER_ROLE, MANAGER_ROLE, SUPERVISOR_ROLE, ACCOUNTANT_ROLE];
export const SALES_DATA_ROLES = [OWNER_ROLE, MANAGER_ROLE, SUPERVISOR_ROLE, SALES_ROLE];
export const INVENTORY_DATA_ROLES = [OWNER_ROLE, MANAGER_ROLE, SUPERVISOR_ROLE, INVENTORY_ROLE];
export const COMMERCIAL_DATA_ROLES = [OWNER_ROLE, MANAGER_ROLE, SUPERVISOR_ROLE, ACCOUNTANT_ROLE];

export const PROVISIONABLE_ROLES = [
  MANAGER_ROLE,
  SUPERVISOR_ROLE,
  OPERATOR_ROLE,
  ACCOUNTANT_ROLE,
  AUDITOR_ROLE,
  ADMIN_ROLE,
  INVENTORY_ROLE,
  SALES_ROLE,
];
