ALTER TYPE "SlabProductionStage" ADD VALUE IF NOT EXISTS 'UNDER_GRINDING';
ALTER TYPE "SlabProductionStage" ADD VALUE IF NOT EXISTS 'GRINDED';
ALTER TYPE "SlabProductionStage" ADD VALUE IF NOT EXISTS 'EPOXY_APPLIED';

CREATE TYPE "LpmProcessType" AS ENUM ('GRINDING', 'POLISHING');

ALTER TABLE "polishing_session"
ADD COLUMN "process_type" "LpmProcessType" NOT NULL DEFAULT 'POLISHING';
